apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{.Release.Name}}
spec:
  type: ClusterIP
  ports:
  - protocol: tcp
    port: 80
    targetPort: 8080
  selector:
    app: {{.Release.Name}}
