apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-arc-sample
  namespace: arc-eks-demo
spec:
  releaseName: arc-eks-demo
  chart:
    git: https://github.com/jf781/arc-helm-demo
    ref: master
    path: charts/azure-arc-sample
  values:
    serviceName: arc-eks-demo